name: 장민수의 블로그
title: MinsooJang
description: Blog of MinsooJang
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: minsoojang@korea.ac.kr
disqus_username: MinsooJang
